In [2]:
%matplotlib inline
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
#from psi import calculate_psi

In [3]:
sns.set_style("white")
rs = np.random.RandomState(5)

In [6]:
initial = rs.normal(size = 100)
initial

array([ 0.79242262,  0.17076445, -1.75374086,  0.63029648,  0.49832921,
        1.01813761, -0.84646862,  2.52080763, -1.23238611,  0.72695326,
        0.04595522, -0.48713265,  0.81613236, -0.28143012, -2.33562182,
       -1.16727845,  0.45765807,  2.23796561, -1.4812592 , -0.01694532,
        1.45073354,  0.60687032, -0.37562084, -1.42192455, -1.7811513 ,
       -0.74790579, -0.36840953, -2.24911813, -1.69367504,  0.30364847,
       -0.40899234, -0.75483059, -0.40751917, -0.81262476,  0.92751621,
        1.63995407,  2.07361553,  0.70979786,  0.74715259,  1.46309548,
        1.73844881,  1.46520488,  1.21228341, -0.6346525 , -1.5996985 ,
        0.87715281, -0.09383245, -0.05567103, -0.88942073, -1.30095145,
        1.40216662,  0.46510099, -1.06503262,  0.39042061,  0.30560017,
        0.52184949,  2.23327081, -0.0347021 , -1.27962318,  0.03654264,
       -0.64635659,  0.54856784,  0.21054246,  0.34650175, -0.56705117,
        0.41367881, -0.51025606,  0.51725935, -0.30100513, -1.11

In [7]:
new = rs.normal(loc = 0.2, size = 120)

In [8]:
new

array([ 0.69961804, -0.95154425, -0.4105164 , -1.50388541,  0.39443738,
        0.22824125,  1.13256051,  0.41204332, -0.16794457,  2.3114884 ,
       -0.82957349, -1.13628031, -0.41056736,  0.72469426, -0.14930813,
       -0.24073846, -0.9212876 ,  1.67284473, -0.42337224, -0.88070195,
        0.07746991, -0.6077431 , -0.03255622,  1.53515034, -0.24645673,
        0.15021132, -0.16854478,  0.00826043,  1.01967992,  0.73163372,
       -0.14161504, -0.73090048,  0.06578301,  1.03259361,  0.18264673,
        0.07234178, -1.60791662,  1.19396898, -1.29112886, -1.08210748,
       -0.17570741,  0.23464388,  0.24507816, -0.56374689, -0.11313851,
       -0.40698954, -1.60955123, -0.05551774, -0.49379935,  0.61919776,
        0.05479981,  1.1638013 ,  0.89622199,  1.09940546,  1.40837807,
        0.8932537 ,  0.03363939,  1.55311311, -0.72862651,  0.16452751,
        1.05964595, -0.08749661,  0.91494995, -0.6034526 , -0.34048196,
        0.74617743,  0.91188926,  1.39715449,  0.12993297,  0.49

In [11]:
def scale_range (input, min, max):
    input += -(np.min(input))
    input /= np.max(input) / (max - min)
    input += min
    return input
buckets = 10
raw_breakpoints = np.arange(0, buckets + 1) / (buckets) * 100
breakpoints = scale_range(raw_breakpoints, np.min(initial), np.max(initial))

In [12]:
breakpoints


array([-2.38669774, -1.89594721, -1.40519667, -0.91444613, -0.42369559,
        0.06705494,  0.55780548,  1.04855602,  1.53930656,  2.0300571 ,
        2.52080763])

In [16]:
initial_counts = np.histogram(initial, breakpoints)[0]
new_counts = np.histogram(new, breakpoints)[0]
print(initial_counts)
print(new_counts)

[ 3  6  9 14 19 20 15  8  2  4]
[ 0  5 10 13 29 18 20 16  4  3]


In [17]:
df = pd.DataFrame({'Bucket': np.arange(1, 11), 'Breakpoint Value':breakpoints[1:], 'Initial Count':initial_counts, 'New Count':new_counts})

In [18]:
df

Bucket  Breakpoint Value  Initial Count  New Count
0       1         -1.895947              3          0
1       2         -1.405197              6          5
2       3         -0.914446              9         10
3       4         -0.423696             14         13
4       5          0.067055             19         29
5       6          0.557805             20         18
6       7          1.048556             15         20
7       8          1.539307              8         16
8       9          2.030057              2          4
9      10          2.520808              4          3

In [21]:
df['Initial Percent'] = df['Initial Count'] / len(initial)
df['New Percent'] = df['New Count'] / len(new)

In [22]:
df['New Percent'][df['New Percent'] == 0] = 0.001

<ipython-input-22-6e6051a78abf>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['New Percent'][df['New Percent'] == 0] = 0.001


In [23]:
df

Bucket  Breakpoint Value  Initial Count  New Count  Initial Percent  \
0       1         -1.895947              3          0             0.03   
1       2         -1.405197              6          5             0.06   
2       3         -0.914446              9         10             0.09   
3       4         -0.423696             14         13             0.14   
4       5          0.067055             19         29             0.19   
5       6          0.557805             20         18             0.20   
6       7          1.048556             15         20             0.15   
7       8          1.539307              8         16             0.08   
8       9          2.030057              2          4             0.02   
9      10          2.520808              4          3             0.04   

   New Percent  
0     0.001000  
1     0.041667  
2     0.083333  
3     0.108333  
4     0.241667  
5     0.150000  
6     0.166667  
7     0.133333  
8     0.033333  
9     0.025000

In [24]:

df['PSI'] = (df['New Percent'] - df['Initial Percent']) * np.log(df['New Percent'] / df['Initial Percent'])

In [26]:
df

Bucket  Breakpoint Value  Initial Count  New Count  Initial Percent  \
0       1         -1.895947              3          0             0.03   
1       2         -1.405197              6          5             0.06   
2       3         -0.914446              9         10             0.09   
3       4         -0.423696             14         13             0.14   
4       5          0.067055             19         29             0.19   
5       6          0.557805             20         18             0.20   
6       7          1.048556             15         20             0.15   
7       8          1.539307              8         16             0.08   
8       9          2.030057              2          4             0.02   
9      10          2.520808              4          3             0.04   

   New Percent       PSI  
0     0.001000  0.098635  
1     0.041667  0.006685  
2     0.083333  0.000513  
3     0.108333  0.008120  
4     0.241667  0.012428  
5     0.150000  0.014384  
6     0.166667  0.001756  
7     0.133333  0.027244  
8     0.033333  0.006811  
9     0.025000  0.007050

In [25]:
np.sum(df['PSI'])

0.18362605493955045

In [1]:
import pandas as pd
import numpy as np
df = pd.read_csv("https://raw.githubusercontent.com/deepanshu88/data/master/data.csv")

In [2]:
df.head()

p  y
0  0.063817  0
1  0.004442  0
2  0.150929  0
3  0.223016  0
4  0.067777  0

In [26]:
df

p  y  y0              bucket
0    0.063817  0   1    (0.0503, 0.0821]
1    0.004442  0   1  (0.00293, 0.00697]
2    0.150929  0   1      (0.135, 0.299]
3    0.223016  0   1      (0.135, 0.299]
4    0.067777  0   1    (0.0503, 0.0821]
..        ... ..  ..                 ...
995  0.002950  0   1  (0.00293, 0.00697]
996  0.014218  0   1    (0.0115, 0.0183]
997  0.076319  0   1    (0.0503, 0.0821]
998  0.006082  0   1  (0.00293, 0.00697]
999  0.255054  0   1      (0.135, 0.299]

[1000 rows x 4 columns]

In [8]:
df['y0']=1-df['y']
df['bucket']=pd.qcut(df['p'],10)
grouped=df.groupby('bucket',as_index=False)
kstable=pd.DataFrame()

In [29]:
df.groupby('bucket',as_index=False).head()

p  y  y0                 bucket
0   0.063817  0   1       (0.0503, 0.0821]
1   0.004442  0   1     (0.00293, 0.00697]
2   0.150929  0   1         (0.135, 0.299]
3   0.223016  0   1         (0.135, 0.299]
4   0.067777  0   1       (0.0503, 0.0821]
5   0.021762  0   1       (0.0183, 0.0294]
6   0.001412  0   1  (-0.0009267, 0.00293]
7   0.009001  0   1      (0.00697, 0.0115]
8   0.166159  0   1         (0.135, 0.299]
9   0.058621  0   1       (0.0503, 0.0821]
10  0.002682  0   1  (-0.0009267, 0.00293]
11  0.001648  0   1  (-0.0009267, 0.00293]
12  0.018714  0   1       (0.0183, 0.0294]
13  0.027675  0   1       (0.0183, 0.0294]
14  0.012030  0   1       (0.0115, 0.0183]
15  0.015738  0   1       (0.0115, 0.0183]
16  0.009152  0   1      (0.00697, 0.0115]
17  0.029527  0   1       (0.0294, 0.0503]
18  0.057653  0   1       (0.0503, 0.0821]
19  0.168831  0   1         (0.135, 0.299]
20  0.117527  0   1        (0.0821, 0.135]
21  0.033225  0   1       (0.0294, 0.0503]
22  0.001009  0   1  (-0.0009267, 0.00293]
23  0.042662  0   1       (0.0294, 0.0503]
24  0.004517  0   1     (0.00293, 0.00697]
25  0.144321  0   1         (0.135, 0.299]
26  0.007321  0   1      (0.00697, 0.0115]
27  0.022779  0   1       (0.0183, 0.0294]
28  0.046477  0   1       (0.0294, 0.0503]
29  0.449333  1   0         (0.299, 0.975]
30  0.001108  0   1  (-0.0009267, 0.00293]
31  0.040051  0   1       (0.0294, 0.0503]
32  0.023413  0   1       (0.0183, 0.0294]
33  0.012453  0   1       (0.0115, 0.0183]
34  0.106419  1   0        (0.0821, 0.135]
35  0.370049  0   1         (0.299, 0.975]
36  0.009142  0   1      (0.00697, 0.0115]
37  0.004485  0   1     (0.00293, 0.00697]
39  0.650697  0   1         (0.299, 0.975]
41  0.011727  0   1       (0.0115, 0.0183]
42  0.061117  0   1       (0.0503, 0.0821]
44  0.010648  0   1      (0.00697, 0.0115]
45  0.094231  0   1        (0.0821, 0.135]
51  0.839416  1   0         (0.299, 0.975]
52  0.005429  0   1     (0.00293, 0.00697]
53  0.126299  1   0        (0.0821, 0.135]
54  0.014773  0   1       (0.0115, 0.0183]
56  0.467743  1   0         (0.299, 0.975]
58  0.006231  0   1     (0.00293, 0.00697]
83  0.115529  1   0        (0.0821, 0.135]

In [24]:
type(grouped)

pandas.core.groupby.generic.DataFrameGroupBy

In [43]:
kstable['min_prob'] = grouped.min()['p']
kstable['max_prob'] = grouped.max()['p']
kstable['events']   = grouped.sum()['y']
kstable['nonevents'] = grouped.sum()['y0']
kstable = kstable.sort_values(by="min_prob", ascending=False).reset_index(drop = True)
kstable['event_rate'] = (kstable.events / df['y'].sum()).apply('{0:.2%}'.format)
kstable['nonevent_rate'] = (kstable.nonevents / df['y0'].sum()).apply('{0:.2%}'.format)
kstable['cum_eventrate']=(kstable.events / df['y'].sum()).cumsum()
kstable['cum_noneventrate']=(kstable.nonevents / df['y0'].sum()).cumsum()
kstable['KS'] = np.round(kstable['cum_eventrate']-kstable['cum_noneventrate'], 3) * 100

In [44]:
kstable

min_prob  max_prob  events  nonevents event_rate nonevent_rate  \
0  0.298894  0.975404      49         51     49.00%         5.67%   
1  0.135598  0.298687      19         81     19.00%         9.00%   
2  0.082170  0.135089      14         86     14.00%         9.56%   
3  0.050369  0.082003      10         90     10.00%        10.00%   
4  0.029415  0.050337       5         95      5.00%        10.56%   
5  0.018343  0.029384       1         99      1.00%        11.00%   
6  0.011504  0.018291       1         99      1.00%        11.00%   
7  0.006976  0.011364       1         99      1.00%        11.00%   
8  0.002929  0.006964       0        100      0.00%        11.11%   
9  0.000073  0.002918       0        100      0.00%        11.11%   

   cum_eventrate  cum_noneventrate    KS  
0           0.49          0.056667  43.3  
1           0.68          0.146667  53.3  
2           0.82          0.242222  57.8  
3           0.92          0.342222  57.8  
4           0.97          0.447778  52.2  
5           0.98          0.557778  42.2  
6           0.99          0.667778  32.2  
7           1.00          0.777778  22.2  
8           1.00          0.888889  11.1  
9           1.00          1.000000   0.0

In [45]:
# Cramer's V calculation.

from itertools import product
import numpy as np
import pandas as pd
import scipy.stats as stats

np.random.seed(42)

all_combs = product(
    ['Spring', 'Summer', 'Fall', 'Winter'],
    ['New', 'Old'],
    ['Cold', 'Warm', 'Hot']
)

df = pd.DataFrame(all_combs, columns=['Season', 'Age', 'Weather'])
df['Sales'] = np.random.randint(25, 200, len(df))
df.head()

Season  Age Weather  Sales
0  Spring  New    Cold    127
1  Spring  New    Warm    117
2  Spring  New     Hot     39
3  Spring  Old    Cold    131
4  Spring  Old    Warm     96

In [48]:
cont = df.pivot_table('Sales', 'Season', 'Weather', 'sum')
cont

Weather  Cold  Hot  Warm
Season                  
Fall      302  181   253
Spring    258   84   213
Summer    239  223   287
Winter    266  247   227

In [49]:
cont_arr = cont.values

In [50]:
cont_arr

array([[302, 181, 253],
       [258,  84, 213],
       [239, 223, 287],
       [266, 247, 227]])

In [51]:
chi2 = stats.chi2_contingency(cont_arr, correction=False)[0]
sample_size = np.sum(cont_arr)
min_dim = min(cont_arr.shape) - 1

cramer_v = np.sqrt((chi2 / sample_size) / min_dim)

cramer_v

0.11434148917987502

In [54]:
cont = df.pivot_table('Sales', 'Season', 'Weather', 'max')
cont

Weather  Cold  Hot  Warm
Season                  
Fall      174  155   176
Spring    131   45   117
Summer    127  124   146
Winter    154  185   182

In [55]:
cont_arr_1 = cont.values

In [56]:
cont_arr_1

array([[174, 155, 176],
       [131,  45, 117],
       [127, 124, 146],
       [154, 185, 182]])

In [57]:
chi2 = stats.chi2_contingency(cont_arr_1, correction=False)[0]
sample_size = np.sum(cont_arr_1)
min_dim = min(cont_arr_1.shape) - 1

cramer_v = np.sqrt((chi2 / sample_size) / min_dim)

cramer_v

0.11024800575776783

In [1]:
p="Hello World"

In [2]:
print(p)

Hello World
